# Generated by Django 3.2.8 on 2021-11-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0002_alter_profile_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='post',
        ),
    ]
