# Generated by Django 3.2.8 on 2021-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0004_comment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='featured_image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
