# Generated by Django 3.2.8 on 2021-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0007_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
