# Generated by Django 3.2.8 on 2021-11-11 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0009_alter_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('body', models.TextField(max_length=2083, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('receipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipient', to='faces_app.profile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faces_app.profile')),
            ],
        ),
    ]
