# Generated by Django 3.2.8 on 2021-11-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0012_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
