# Generated by Django 3.2.8 on 2021-11-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0013_alter_comment_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
