# Generated by Django 3.2.8 on 2021-11-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0014_auto_20211112_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_image',
        ),
    ]
