# Generated by Django 3.2.8 on 2021-11-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0019_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
